from fpdf import FPDF
from datetime import datetime, timezone, timedelta
from config import SOURCE_LABELS
import unicodedata

SGT = timezone(timedelta(hours=8))


def sanitize(text: str) -> str:
    if not text:
        return ""
    text = unicodedata.normalize("NFKD", text)
    text = text.encode("ascii", "ignore").decode("ascii")
    text = text.replace("\u2013", "-").replace("\u2014", "--")
    text = text.replace("\u2018", "'").replace("\u2019", "'")
    text = text.replace("\u201c", '"').replace("\u201d", '"')
    text = text.replace("\u2026", "...").replace("\u00a0", " ")
    return text


def clean_text(text) -> str:
    if text is None:
        return ""
    t = str(text).replace("_x000D_", " ").replace("_x000D", " ")
    t = t.replace("\uFFFD", "")
    return sanitize(t)


HIT_COLOR = (200, 50, 50)
POTENTIAL_COLOR = (180, 130, 0)
INK = (17, 17, 17)
ROW_HILITE = (247, 241, 220)
GOLD = (229, 169, 19)


class ScreeningReport(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=25)

    def header(self):
        self.set_fill_color(17, 17, 17)  # #111111
        self.rect(0, 0, 210, 12, "F")
        self.set_text_color(229, 169, 19)  # #E5A913
        self.set_font("Helvetica", "B", 10)
        self.cell(0, 12, "SENTINEL", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_text_color(17, 17, 17)
        self.set_draw_color(229, 169, 19)
        self.line(10, 14, 200, 14)
        self.ln(6)

    def footer(self):
        self.set_y(-20)
        self.set_font("Helvetica", "I", 6)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, "This report reflects the sanctions and enforcement list data available at the time of screening,", align="C")
        self.ln(3)
        self.cell(0, 5, "as detailed in the Data Provenance table. Screening results are advisory and generated by automated", align="C")
        self.ln(3)
        self.cell(0, 5, "name-matching algorithms. Matches require human review and confirmation against the underlying source", align="C")
        self.ln(3)
        self.cell(0, 5, "records before any action is taken. This tool accepts no liability for reliance on this report without", align="C")
        self.ln(3)
        self.cell(0, 5, f"independent verification. Page {self.page_no()}/{{nb}}", align="C")


def draw_verdict_banner(pdf: ScreeningReport, verdict: str):
    pdf.set_font("Helvetica", "B", 24)
    if verdict == "HIT":
        pdf.set_fill_color(200, 50, 50)
        pdf.set_text_color(255, 255, 255)
        label = "FLAGGED"
    elif verdict == "POTENTIAL HIT":
        pdf.set_fill_color(229, 169, 19)
        pdf.set_text_color(17, 17, 17)
        label = "POTENTIAL MATCH"
    else:
        pdf.set_fill_color(50, 180, 100)
        pdf.set_text_color(255, 255, 255)
        label = "NOT FLAGGED"
    pdf.cell(0, 20, f"  {label}", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(17, 17, 17)
    pdf.ln(4)


def draw_provenance_table(pdf: ScreeningReport, sources: dict):
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_fill_color(17, 17, 17)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(0, 8, "Data Provenance", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(17, 17, 17)
    pdf.ln(2)

    col_w = [60, 25, 30, 55]
    headers = ["Source", "Status", "Records", "Fetched At"]
    pdf.set_font("Helvetica", "B", 8)
    pdf.set_fill_color(245, 245, 245)
    for i, h in enumerate(headers):
        pdf.cell(col_w[i], 7, h, border=1, fill=True)
    pdf.ln()

    pdf.set_font("Helvetica", "", 7)
    for src_key, src_data in sources.items():
        label = SOURCE_LABELS.get(src_key, src_key)
        status = src_data.get("status", "unknown").upper()
        count = str(src_data.get("record_count", 0))

        fetched = src_data.get("fetched_at", "")
        if fetched:
            try:
                dt = datetime.fromisoformat(fetched.replace("Z", "+00:00"))
                fetched = dt.astimezone(SGT).strftime("%Y-%m-%d %H:%M SGT")
            except (ValueError, AttributeError):
                fetched = fetched[:19]
        else:
            fetched = "-"

        if status == "LIVE":
            status_display = "LIVE"
        elif status == "CACHED":
            status_display = "CACHED"
        else:
            status_display = "FAILED"

        pdf.cell(col_w[0], 6, sanitize(label), border=1)
        pdf.cell(col_w[1], 6, status_display, border=1)
        pdf.cell(col_w[2], 6, count, border=1)
        pdf.cell(col_w[3], 6, sanitize(fetched), border=1)
        pdf.ln()

    pdf.ln(4)


def _cell_h(pdf, width, text, line_h):
    if not text:
        return 0.0
    return pdf.multi_cell(width, line_h, str(text), dry_run=True, output="HEIGHT")


def _fit(pdf, text, width, size=12):
    pdf.set_font("Helvetica", "B", size)
    if pdf.get_string_width(text) <= width:
        return text
    while text and pdf.get_string_width(text + "...") > width:
        text = text[:-1]
    return text + "..."


def _card_layout(pdf, record, source):
    x0 = pdf.l_margin
    total_w = 210 - 2 * x0
    label_w = 26
    value_w = total_w - label_w
    grid_label_w = 26
    half_value = (total_w - label_w) // 2 - grid_label_w
    line_h = 4.4
    title_h = 6.5

    grid = [
        ("TYPE", clean_text(record.get("entity_type", ""))),
        ("DOB", clean_text(record.get("dob", ""))),
        ("NATIONALITY", clean_text(record.get("nationality", ""))),
        ("SOURCE", source),
    ]
    wrapped = [
        ("PROGRAMS", clean_text("; ".join(record.get("programs", [])))),
        ("ALIASES", clean_text("; ".join(record.get("aliases", [])[:5]))),
        ("REMARKS", clean_text(record.get("remarks", ""))),
    ]

    pdf.set_font("Helvetica", "", 8)
    rows = []
    for i in (0, 2):
        pairs = [grid[i], grid[i + 1]]
        if not any(v for _, v in pairs):
            continue
        h = max(_cell_h(pdf, half_value, v, line_h) for _, v in pairs if v)
        rows.append(("grid", pairs, h))
    for label, v in wrapped:
        if v:
            rows.append(("field", (label, v), _cell_h(pdf, value_w, v, line_h)))

    est_h = title_h + sum(row[2] for row in rows) + 2.5
    return {
        "rows": rows,
        "est_h": est_h,
        "x0": x0,
        "total_w": total_w,
        "label_w": label_w,
        "value_w": value_w,
        "grid_label_w": grid_label_w,
        "half_value": half_value,
        "line_h": line_h,
        "title_h": title_h,
    }


def card_height(pdf, match, index):
    record = match.get("record", {})
    source = clean_text(record.get("source_label", record.get("source", "")))
    return _card_layout(pdf, record, source)["est_h"]


def draw_match_card(pdf: ScreeningReport, match: dict, index: int):
    record = match.get("record", {})
    is_best = (index == 0)
    source = clean_text(record.get("source_label", record.get("source", "")))
    L = _card_layout(pdf, record, source)
    x0 = L["x0"]
    total_w = L["total_w"]
    label_w = L["label_w"]
    value_w = L["value_w"]
    grid_label_w = L["grid_label_w"]
    half_value = L["half_value"]
    line_h = L["line_h"]
    title_h = L["title_h"]
    rows = L["rows"]
    est_h = L["est_h"]

    confidence = match.get("confidence", 0)
    matched_name = clean_text(match.get("matched_name") or record.get("name", ""))
    if confidence >= 95:
        conf_color = (50, 180, 100)
    elif confidence >= 85:
        conf_color = POTENTIAL_COLOR
    else:
        conf_color = HIT_COLOR

    if pdf.will_page_break(est_h):
        pdf.add_page()
    top = pdf.get_y()

    if is_best:
        pdf.set_fill_color(*ROW_HILITE)
        pdf.rect(x0, top, total_w, est_h, "F")
        pdf.set_fill_color(*GOLD)
        pdf.rect(x0, top, 1.2, est_h, "F")

    pdf.set_font("Helvetica", "B", 9)
    conf_str = f"{confidence}%"
    cw = pdf.get_string_width(conf_str)

    pdf.set_font("Helvetica", "B", 9)
    prefix = f"  Match #{index + 1}  "
    pref_w = pdf.get_string_width(prefix)
    pdf.set_font("Helvetica", "", 7.5)
    src_w = pdf.get_string_width(source)
    name_budget = total_w - cw - src_w - pref_w - 11
    name = _fit(pdf, matched_name, name_budget, size=9)

    pdf.set_xy(x0, top)
    pdf.set_text_color(*INK)
    pdf.set_font("Helvetica", "B", 9)
    pdf.cell(pref_w, title_h, prefix, new_x="RIGHT", new_y="TOP")
    pdf.cell(pdf.get_string_width(name), title_h, name, new_x="RIGHT", new_y="TOP")
    pdf.cell(3, title_h, "", new_x="RIGHT", new_y="TOP")
    pdf.set_font("Helvetica", "", 7.5)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(src_w, title_h, source, new_x="RIGHT", new_y="TOP")
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_text_color(*conf_color)
    pdf.set_xy(x0 + total_w - cw - 3, top)
    pdf.cell(cw, title_h, conf_str, align="R")

    y = top + title_h
    for row in rows:
        if row[0] == "grid":
            _, pairs, row_h = row
            for k, (label, value) in enumerate(pairs):
                if not value:
                    continue
                cx = x0 + k * (grid_label_w + half_value)
                pdf.set_xy(cx, y)
                pdf.set_font("Helvetica", "B", 7.5)
                pdf.set_text_color(110, 110, 110)
                pdf.cell(grid_label_w, line_h, label + ":", new_x="RIGHT", new_y="TOP")
                pdf.set_font("Helvetica", "", 8)
                pdf.set_text_color(*INK)
                pdf.multi_cell(half_value, line_h, value, new_x="RIGHT", new_y="TOP")
            y += row_h
        else:
            _, (label, value), row_h = row
            pdf.set_xy(x0, y)
            pdf.set_font("Helvetica", "B", 7.5)
            pdf.set_text_color(110, 110, 110)
            pdf.cell(label_w, line_h, label + ":", new_x="RIGHT", new_y="TOP")
            pdf.set_font("Helvetica", "", 8)
            pdf.set_text_color(*INK)
            pdf.multi_cell(value_w, line_h, value, new_x="LMARGIN", new_y="NEXT")
            y += row_h

    pdf.set_xy(x0, y + 6)


def draw_name_header(pdf, num, query, verdict, top_conf, top_source):
    pdf.set_fill_color(17, 17, 17)
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(255, 255, 255)
    left = f"  {num}. {_fit(pdf, clean_text(query), 104)}"
    pdf.cell(112, 10, left, fill=True, new_x="RIGHT", new_y="TOP")
    pdf.set_font("Helvetica", "B", 10)
    if verdict == "HIT":
        pdf.set_text_color(255, 125, 125)
    else:
        pdf.set_text_color(240, 205, 90)
    right = f"{verdict}  {top_conf}%  {_fit(pdf, clean_text(top_source), 42, size=10)}"
    pdf.cell(78, 10, right, align="R", fill=True, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(*INK)
    pdf.ln(4)


def generate_single_search_report(query: str, result: dict, sources: dict) -> bytes:
    pdf = ScreeningReport()
    pdf.alias_nb_pages()
    pdf.add_page()

    draw_verdict_banner(pdf, result.get("verdict", "NO HIT"))

    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 5, sanitize(f"Query: {query}"), new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, f"Screened at: {datetime.now(SGT).strftime('%Y-%m-%d %H:%M SGT')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, f"Total records screened: {result.get('total_records_screened', 0)}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, f"Matches found: {result.get('match_count', 0)}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    draw_provenance_table(pdf, sources)

    for i, m in enumerate(result.get("matches", [])):
        if pdf.get_y() > 240:
            pdf.add_page()
        draw_match_card(pdf, m, i)

    return bytes(pdf.output())


def generate_bulk_screening_report(results: dict, sources: dict, meta: dict = None) -> bytes:
    pdf = ScreeningReport()
    pdf.alias_nb_pages()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 18)
    pdf.set_text_color(17, 17, 17)
    pdf.cell(0, 12, "Bulk Screening Report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 9)
    pdf.cell(0, 5, "Prepared by: SENTINEL", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 5, f"Generated: {datetime.now(SGT).strftime('%Y-%m-%d %H:%M SGT')}", new_x="LMARGIN", new_y="NEXT")
    if meta and "filename" in meta:
        pdf.cell(0, 5, sanitize(f"Source file: {meta['filename']}"), new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    total = results.get("total", 0)
    hits = results.get("hit_count", 0)
    potentials = results.get("potential_count", 0)
    cleans = results.get("no_hit_count", 0)

    pdf.set_font("Helvetica", "B", 16)
    pdf.cell(0, 10, f"Total: {total}  |  FLAGGED: {hits}  |  POTENTIAL: {potentials}  |  CLEAR: {cleans}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(4)

    draw_provenance_table(pdf, sources)

    col_w = [70, 22, 22, 76]
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_fill_color(17, 17, 17)
    pdf.set_text_color(255, 255, 255)
    for i, h in enumerate(["Name", "Verdict", "Confidence", "Top Match Source"]):
        pdf.cell(col_w[i], 7, h, border=1, fill=True)
    pdf.ln()
    pdf.set_text_color(17, 17, 17)

    pdf.set_font("Helvetica", "", 8)
    for r in results.get("results", []):
        query = r.get("query", "")
        verdict = r.get("verdict", "")
        top_conf = r.get("top_confidence", 0)
        matches = r.get("matches", [])
        top_source = matches[0]["record"].get("source_label", "") if matches else ""

        if verdict == "HIT":
            pdf.set_text_color(*HIT_COLOR)
        elif verdict == "POTENTIAL HIT":
            pdf.set_text_color(*POTENTIAL_COLOR)
        else:
            pdf.set_text_color(50, 180, 100)

        if pdf.will_page_break(6):
            pdf.add_page()
            pdf.set_font("Helvetica", "B", 9)
            for i, h in enumerate(["Name", "Verdict", "Confidence", "Top Match Source"]):
                pdf.cell(col_w[i], 7, h, border=1)
            pdf.ln()
            pdf.set_font("Helvetica", "", 8)

        pdf.cell(col_w[0], 6, sanitize(query[:40]), border=1)
        pdf.cell(col_w[1], 6, sanitize(verdict), border=1)
        pdf.cell(col_w[2], 6, str(top_conf), border=1)
        pdf.cell(col_w[3], 6, sanitize(top_source[:40]), border=1)
        pdf.ln()

    pdf.set_text_color(17, 17, 17)
    pdf.ln(6)

    num = 0
    for r in results.get("results", []):
        if r["verdict"] not in ("HIT", "POTENTIAL HIT"):
            continue
        matches = r.get("matches", [])[:10]
        if not matches:
            continue
        num += 1
        top = matches[0]
        top_source = top["record"].get("source_label", top["record"].get("source", ""))
        if pdf.will_page_break(14.5 + card_height(pdf, top, 0)):
            pdf.add_page()
        draw_name_header(pdf, num, r["query"], r["verdict"], top["confidence"], top_source)
        for mi, m in enumerate(matches):
            draw_match_card(pdf, m, mi)
        pdf.ln(1.5)

    return bytes(pdf.output())
